// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services.proto

package org.example.services;

public final class Services {
  private Services() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016services.proto\032\033google/protobuf/empty." +
      "proto\032\020data_types.proto2g\n ElectionResul" +
      "tDeclarationService\022C\n\rdeclareResult\022\032.E" +
      "lectionResultDeclaration\032\026.google.protob" +
      "uf.Empty2I\n\026ElectionRequestService\022/\n\013el" +
      "ectLeader\022\020.ElectionRequest\032\016.ElectionRe" +
      "ply2H\n\022TransactionService\0222\n\010transact\022\023." +
      "TransactionRequest\032\021.TransactionReply2k\n" +
      "\027ResetSellerOnOutOfStock\022P\n\013resetSeller\022" +
      "\035.SellerOutOfStockNotification\032\".SellerO" +
      "utOfStockNotificationReply2n\n$LeaderResi" +
      "gnationNotificationService\022F\n\014resignLead" +
      "er\022\036.LeaderResignationNotification\032\026.goo" +
      "gle.protobuf.Empty2e\n\033LeaderInitializati" +
      "onService\022F\n\016initiateLeader\022\034.LeaderInit" +
      "ializationRequest\032\026.google.protobuf.Empt" +
      "yB\030\n\024org.example.servicesP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          org.example.data_types.DataTypes.getDescriptor(),
        }, assigner);
    com.google.protobuf.EmptyProto.getDescriptor();
    org.example.data_types.DataTypes.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
