// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services.proto

package org.example.services;

public final class Services {
  private Services() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016services.proto\032\033google/protobuf/empty." +
      "proto\032\020data_types.proto2\\\n\025ElectionResul" +
      "tService\022C\n\rdeclareResult\022\032.ElectionResu" +
      "ltDeclaration\032\026.google.protobuf.Empty2B\n" +
      "\017ElectionService\022/\n\013electLeader\022\020.Electi" +
      "onRequest\032\016.ElectionReply2H\n\022Transaction" +
      "Service\0222\n\010transact\022\023.TransactionRequest" +
      "\032\021.TransactionReplyB\030\n\024org.example.servi" +
      "cesP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          org.example.data_types.DataTypes.getDescriptor(),
        }, assigner);
    com.google.protobuf.EmptyProto.getDescriptor();
    org.example.data_types.DataTypes.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
