// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_types.proto

package org.example.data_types;

public interface ElectionReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ElectionReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 initiatorId = 1;</code>
   */
  int getInitiatorId();

  /**
   * <code>uint32 leaderId = 2;</code>
   */
  int getLeaderId();

  /**
   * <code>uint32 leaderVoterId = 3;</code>
   */
  int getLeaderVoterId();

  /**
   * <code>repeated uint32 path = 4;</code>
   */
  java.util.List<java.lang.Integer> getPathList();
  /**
   * <code>repeated uint32 path = 4;</code>
   */
  int getPathCount();
  /**
   * <code>repeated uint32 path = 4;</code>
   */
  int getPath(int index);
}
