// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_types.proto

package org.example.data_types;

public interface ElectionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ElectionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 contenderId = 1;</code>
   */
  int getContenderId();

  /**
   * <code>uint32 contenderVoterId = 2;</code>
   */
  int getContenderVoterId();

  /**
   * <code>repeated uint32 path = 3;</code>
   */
  java.util.List<java.lang.Integer> getPathList();
  /**
   * <code>repeated uint32 path = 3;</code>
   */
  int getPathCount();
  /**
   * <code>repeated uint32 path = 3;</code>
   */
  int getPath(int index);

  /**
   * <code>bool isInitiator = 4;</code>
   */
  boolean getIsInitiator();

  /**
   * <code>uint64 clock = 5;</code>
   */
  long getClock();
}
