// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_types.proto

package org.example.data_types;

public interface ElectionResultDeclarationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ElectionResultDeclaration)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 leader_id = 1;</code>
   */
  int getLeaderId();
}
