// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_types.proto

package org.example.data_types;

/**
 * Protobuf type {@code ElectionResultDeclaration}
 */
public  final class ElectionResultDeclaration extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ElectionResultDeclaration)
    ElectionResultDeclarationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ElectionResultDeclaration.newBuilder() to construct.
  private ElectionResultDeclaration(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ElectionResultDeclaration() {
    leaderId_ = 0;
    leaderVoterId_ = 0;
    path_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ElectionResultDeclaration(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            leaderId_ = input.readUInt32();
            break;
          }
          case 16: {

            leaderVoterId_ = input.readUInt32();
            break;
          }
          case 24: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              path_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000004;
            }
            path_.add(input.readUInt32());
            break;
          }
          case 26: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
              path_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000004;
            }
            while (input.getBytesUntilLimit() > 0) {
              path_.add(input.readUInt32());
            }
            input.popLimit(limit);
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        path_ = java.util.Collections.unmodifiableList(path_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.example.data_types.DataTypes.internal_static_ElectionResultDeclaration_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.example.data_types.DataTypes.internal_static_ElectionResultDeclaration_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.example.data_types.ElectionResultDeclaration.class, org.example.data_types.ElectionResultDeclaration.Builder.class);
  }

  private int bitField0_;
  public static final int LEADERID_FIELD_NUMBER = 1;
  private int leaderId_;
  /**
   * <code>uint32 leaderId = 1;</code>
   */
  public int getLeaderId() {
    return leaderId_;
  }

  public static final int LEADERVOTERID_FIELD_NUMBER = 2;
  private int leaderVoterId_;
  /**
   * <code>uint32 leaderVoterId = 2;</code>
   */
  public int getLeaderVoterId() {
    return leaderVoterId_;
  }

  public static final int PATH_FIELD_NUMBER = 3;
  private java.util.List<java.lang.Integer> path_;
  /**
   * <code>repeated uint32 path = 3;</code>
   */
  public java.util.List<java.lang.Integer>
      getPathList() {
    return path_;
  }
  /**
   * <code>repeated uint32 path = 3;</code>
   */
  public int getPathCount() {
    return path_.size();
  }
  /**
   * <code>repeated uint32 path = 3;</code>
   */
  public int getPath(int index) {
    return path_.get(index);
  }
  private int pathMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (leaderId_ != 0) {
      output.writeUInt32(1, leaderId_);
    }
    if (leaderVoterId_ != 0) {
      output.writeUInt32(2, leaderVoterId_);
    }
    if (getPathList().size() > 0) {
      output.writeUInt32NoTag(26);
      output.writeUInt32NoTag(pathMemoizedSerializedSize);
    }
    for (int i = 0; i < path_.size(); i++) {
      output.writeUInt32NoTag(path_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (leaderId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, leaderId_);
    }
    if (leaderVoterId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, leaderVoterId_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < path_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeUInt32SizeNoTag(path_.get(i));
      }
      size += dataSize;
      if (!getPathList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      pathMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.example.data_types.ElectionResultDeclaration)) {
      return super.equals(obj);
    }
    org.example.data_types.ElectionResultDeclaration other = (org.example.data_types.ElectionResultDeclaration) obj;

    boolean result = true;
    result = result && (getLeaderId()
        == other.getLeaderId());
    result = result && (getLeaderVoterId()
        == other.getLeaderVoterId());
    result = result && getPathList()
        .equals(other.getPathList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LEADERID_FIELD_NUMBER;
    hash = (53 * hash) + getLeaderId();
    hash = (37 * hash) + LEADERVOTERID_FIELD_NUMBER;
    hash = (53 * hash) + getLeaderVoterId();
    if (getPathCount() > 0) {
      hash = (37 * hash) + PATH_FIELD_NUMBER;
      hash = (53 * hash) + getPathList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.example.data_types.ElectionResultDeclaration parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.data_types.ElectionResultDeclaration parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.data_types.ElectionResultDeclaration parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.data_types.ElectionResultDeclaration parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.data_types.ElectionResultDeclaration parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.data_types.ElectionResultDeclaration parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.data_types.ElectionResultDeclaration parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.data_types.ElectionResultDeclaration parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.data_types.ElectionResultDeclaration parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.example.data_types.ElectionResultDeclaration parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.data_types.ElectionResultDeclaration parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.data_types.ElectionResultDeclaration parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.example.data_types.ElectionResultDeclaration prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ElectionResultDeclaration}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ElectionResultDeclaration)
      org.example.data_types.ElectionResultDeclarationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.data_types.DataTypes.internal_static_ElectionResultDeclaration_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.data_types.DataTypes.internal_static_ElectionResultDeclaration_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.data_types.ElectionResultDeclaration.class, org.example.data_types.ElectionResultDeclaration.Builder.class);
    }

    // Construct using org.example.data_types.ElectionResultDeclaration.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      leaderId_ = 0;

      leaderVoterId_ = 0;

      path_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.example.data_types.DataTypes.internal_static_ElectionResultDeclaration_descriptor;
    }

    @java.lang.Override
    public org.example.data_types.ElectionResultDeclaration getDefaultInstanceForType() {
      return org.example.data_types.ElectionResultDeclaration.getDefaultInstance();
    }

    @java.lang.Override
    public org.example.data_types.ElectionResultDeclaration build() {
      org.example.data_types.ElectionResultDeclaration result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.example.data_types.ElectionResultDeclaration buildPartial() {
      org.example.data_types.ElectionResultDeclaration result = new org.example.data_types.ElectionResultDeclaration(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.leaderId_ = leaderId_;
      result.leaderVoterId_ = leaderVoterId_;
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        path_ = java.util.Collections.unmodifiableList(path_);
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.path_ = path_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.example.data_types.ElectionResultDeclaration) {
        return mergeFrom((org.example.data_types.ElectionResultDeclaration)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.example.data_types.ElectionResultDeclaration other) {
      if (other == org.example.data_types.ElectionResultDeclaration.getDefaultInstance()) return this;
      if (other.getLeaderId() != 0) {
        setLeaderId(other.getLeaderId());
      }
      if (other.getLeaderVoterId() != 0) {
        setLeaderVoterId(other.getLeaderVoterId());
      }
      if (!other.path_.isEmpty()) {
        if (path_.isEmpty()) {
          path_ = other.path_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensurePathIsMutable();
          path_.addAll(other.path_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.example.data_types.ElectionResultDeclaration parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.example.data_types.ElectionResultDeclaration) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int leaderId_ ;
    /**
     * <code>uint32 leaderId = 1;</code>
     */
    public int getLeaderId() {
      return leaderId_;
    }
    /**
     * <code>uint32 leaderId = 1;</code>
     */
    public Builder setLeaderId(int value) {
      
      leaderId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 leaderId = 1;</code>
     */
    public Builder clearLeaderId() {
      
      leaderId_ = 0;
      onChanged();
      return this;
    }

    private int leaderVoterId_ ;
    /**
     * <code>uint32 leaderVoterId = 2;</code>
     */
    public int getLeaderVoterId() {
      return leaderVoterId_;
    }
    /**
     * <code>uint32 leaderVoterId = 2;</code>
     */
    public Builder setLeaderVoterId(int value) {
      
      leaderVoterId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 leaderVoterId = 2;</code>
     */
    public Builder clearLeaderVoterId() {
      
      leaderVoterId_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Integer> path_ = java.util.Collections.emptyList();
    private void ensurePathIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        path_ = new java.util.ArrayList<java.lang.Integer>(path_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <code>repeated uint32 path = 3;</code>
     */
    public java.util.List<java.lang.Integer>
        getPathList() {
      return java.util.Collections.unmodifiableList(path_);
    }
    /**
     * <code>repeated uint32 path = 3;</code>
     */
    public int getPathCount() {
      return path_.size();
    }
    /**
     * <code>repeated uint32 path = 3;</code>
     */
    public int getPath(int index) {
      return path_.get(index);
    }
    /**
     * <code>repeated uint32 path = 3;</code>
     */
    public Builder setPath(
        int index, int value) {
      ensurePathIsMutable();
      path_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated uint32 path = 3;</code>
     */
    public Builder addPath(int value) {
      ensurePathIsMutable();
      path_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated uint32 path = 3;</code>
     */
    public Builder addAllPath(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensurePathIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, path_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated uint32 path = 3;</code>
     */
    public Builder clearPath() {
      path_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ElectionResultDeclaration)
  }

  // @@protoc_insertion_point(class_scope:ElectionResultDeclaration)
  private static final org.example.data_types.ElectionResultDeclaration DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.example.data_types.ElectionResultDeclaration();
  }

  public static org.example.data_types.ElectionResultDeclaration getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ElectionResultDeclaration>
      PARSER = new com.google.protobuf.AbstractParser<ElectionResultDeclaration>() {
    @java.lang.Override
    public ElectionResultDeclaration parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ElectionResultDeclaration(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ElectionResultDeclaration> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ElectionResultDeclaration> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.example.data_types.ElectionResultDeclaration getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

