// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_types.proto

package org.example.data_types;

public interface LeaderInitializationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LeaderInitializationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 initiator_id = 1;</code>
   */
  int getInitiatorId();
}
