// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_types.proto

package org.example.data_types;

/**
 * Protobuf type {@code LeaderResignationNotification}
 */
public  final class LeaderResignationNotification extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:LeaderResignationNotification)
    LeaderResignationNotificationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LeaderResignationNotification.newBuilder() to construct.
  private LeaderResignationNotification(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LeaderResignationNotification() {
    leaderId_ = 0;
    clock_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LeaderResignationNotification(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            leaderId_ = input.readUInt32();
            break;
          }
          case 16: {

            clock_ = input.readUInt64();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.example.data_types.DataTypes.internal_static_LeaderResignationNotification_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.example.data_types.DataTypes.internal_static_LeaderResignationNotification_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.example.data_types.LeaderResignationNotification.class, org.example.data_types.LeaderResignationNotification.Builder.class);
  }

  public static final int LEADER_ID_FIELD_NUMBER = 1;
  private int leaderId_;
  /**
   * <code>uint32 leader_id = 1;</code>
   */
  public int getLeaderId() {
    return leaderId_;
  }

  public static final int CLOCK_FIELD_NUMBER = 2;
  private long clock_;
  /**
   * <code>uint64 clock = 2;</code>
   */
  public long getClock() {
    return clock_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (leaderId_ != 0) {
      output.writeUInt32(1, leaderId_);
    }
    if (clock_ != 0L) {
      output.writeUInt64(2, clock_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (leaderId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, leaderId_);
    }
    if (clock_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, clock_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.example.data_types.LeaderResignationNotification)) {
      return super.equals(obj);
    }
    org.example.data_types.LeaderResignationNotification other = (org.example.data_types.LeaderResignationNotification) obj;

    boolean result = true;
    result = result && (getLeaderId()
        == other.getLeaderId());
    result = result && (getClock()
        == other.getClock());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LEADER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getLeaderId();
    hash = (37 * hash) + CLOCK_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getClock());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.example.data_types.LeaderResignationNotification parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.data_types.LeaderResignationNotification parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.data_types.LeaderResignationNotification parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.data_types.LeaderResignationNotification parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.data_types.LeaderResignationNotification parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.data_types.LeaderResignationNotification parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.data_types.LeaderResignationNotification parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.data_types.LeaderResignationNotification parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.data_types.LeaderResignationNotification parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.example.data_types.LeaderResignationNotification parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.data_types.LeaderResignationNotification parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.data_types.LeaderResignationNotification parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.example.data_types.LeaderResignationNotification prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code LeaderResignationNotification}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:LeaderResignationNotification)
      org.example.data_types.LeaderResignationNotificationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.data_types.DataTypes.internal_static_LeaderResignationNotification_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.data_types.DataTypes.internal_static_LeaderResignationNotification_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.data_types.LeaderResignationNotification.class, org.example.data_types.LeaderResignationNotification.Builder.class);
    }

    // Construct using org.example.data_types.LeaderResignationNotification.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      leaderId_ = 0;

      clock_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.example.data_types.DataTypes.internal_static_LeaderResignationNotification_descriptor;
    }

    @java.lang.Override
    public org.example.data_types.LeaderResignationNotification getDefaultInstanceForType() {
      return org.example.data_types.LeaderResignationNotification.getDefaultInstance();
    }

    @java.lang.Override
    public org.example.data_types.LeaderResignationNotification build() {
      org.example.data_types.LeaderResignationNotification result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.example.data_types.LeaderResignationNotification buildPartial() {
      org.example.data_types.LeaderResignationNotification result = new org.example.data_types.LeaderResignationNotification(this);
      result.leaderId_ = leaderId_;
      result.clock_ = clock_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.example.data_types.LeaderResignationNotification) {
        return mergeFrom((org.example.data_types.LeaderResignationNotification)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.example.data_types.LeaderResignationNotification other) {
      if (other == org.example.data_types.LeaderResignationNotification.getDefaultInstance()) return this;
      if (other.getLeaderId() != 0) {
        setLeaderId(other.getLeaderId());
      }
      if (other.getClock() != 0L) {
        setClock(other.getClock());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.example.data_types.LeaderResignationNotification parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.example.data_types.LeaderResignationNotification) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int leaderId_ ;
    /**
     * <code>uint32 leader_id = 1;</code>
     */
    public int getLeaderId() {
      return leaderId_;
    }
    /**
     * <code>uint32 leader_id = 1;</code>
     */
    public Builder setLeaderId(int value) {
      
      leaderId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 leader_id = 1;</code>
     */
    public Builder clearLeaderId() {
      
      leaderId_ = 0;
      onChanged();
      return this;
    }

    private long clock_ ;
    /**
     * <code>uint64 clock = 2;</code>
     */
    public long getClock() {
      return clock_;
    }
    /**
     * <code>uint64 clock = 2;</code>
     */
    public Builder setClock(long value) {
      
      clock_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 clock = 2;</code>
     */
    public Builder clearClock() {
      
      clock_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:LeaderResignationNotification)
  }

  // @@protoc_insertion_point(class_scope:LeaderResignationNotification)
  private static final org.example.data_types.LeaderResignationNotification DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.example.data_types.LeaderResignationNotification();
  }

  public static org.example.data_types.LeaderResignationNotification getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LeaderResignationNotification>
      PARSER = new com.google.protobuf.AbstractParser<LeaderResignationNotification>() {
    @java.lang.Override
    public LeaderResignationNotification parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LeaderResignationNotification(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LeaderResignationNotification> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LeaderResignationNotification> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.example.data_types.LeaderResignationNotification getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

