// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_types.proto

package org.example.data_types;

public interface LookupRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LookupRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 buyer_id = 1;</code>
   */
  int getBuyerId();

  /**
   * <code>string product_name = 2;</code>
   */
  java.lang.String getProductName();
  /**
   * <code>string product_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getProductNameBytes();

  /**
   * <code>uint32 hops = 3;</code>
   */
  int getHops();

  /**
   * <code>uint64 request_id = 4;</code>
   */
  long getRequestId();

  /**
   * <code>repeated uint32 path = 5;</code>
   */
  java.util.List<java.lang.Integer> getPathList();
  /**
   * <code>repeated uint32 path = 5;</code>
   */
  int getPathCount();
  /**
   * <code>repeated uint32 path = 5;</code>
   */
  int getPath(int index);
}
