// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_types.proto

package org.example.data_types;

public interface SellerOutOfStockNotificationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SellerOutOfStockNotification)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 trader_id = 1;</code>
   */
  int getTraderId();
}
