// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_types.proto

package org.example.data_types;

public interface SellerOutOfStockNotificationReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SellerOutOfStockNotificationReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 seller_id = 1;</code>
   */
  int getSellerId();

  /**
   * <code>string product_name = 2;</code>
   */
  java.lang.String getProductName();
  /**
   * <code>string product_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getProductNameBytes();

  /**
   * <code>uint32 qty = 3;</code>
   */
  int getQty();

  /**
   * <code>uint32 price = 4;</code>
   */
  int getPrice();
}
