// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_types.proto

package org.example.data_types;

public interface SellerReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SellerReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 seller_id = 1;</code>
   */
  int getSellerId();

  /**
   * <code>uint64 request_id = 2;</code>
   */
  long getRequestId();

  /**
   * <code>repeated uint32 path = 3;</code>
   */
  java.util.List<java.lang.Integer> getPathList();
  /**
   * <code>repeated uint32 path = 3;</code>
   */
  int getPathCount();
  /**
   * <code>repeated uint32 path = 3;</code>
   */
  int getPath(int index);
}
