// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_types.proto

package org.example.data_types;

public interface TransactionReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TransactionReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool status_code = 1;</code>
   */
  boolean getStatusCode();
}
